name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Set the Python version as required

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bzip2 tar

    - name: Prepare files
      run: | # release version with tag name
        tar -cjvf release-files.tar.bz2 --exclude='.git' --exclude='.github' .

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./release-files.tar.bz2
        asset_name: release-files.tar.bz2
        asset_content_type: application/x-bzip2