name: Release Workflow

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  actions: read
  
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: vcp

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bzip2 tar

    - name: Prepare files
      run: |
        tar cjvf release-files.tar.bz2 --exclude='.git' --exclude='.github' ./*

    - name: Create SHA256 file
      run: |
        shasum -a 256 release-files.tar.bz2  | awk '{print $1}' | tee > release-files.tar.bz2.sha256

    - name: Print out the size of the release file
      run: |
        stat --printf="%s\n" release-files.tar.bz2

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release-files.tar.bz2
          release-files.tar.bz2.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
